### ISSUE TITLE
能给docker-compose吗？

### ISSUE THREAD

**Issue by czxinshui** [roiding/docker-cloudflare-warp#1]
这个里面需要什么变量？可以告知一下吗

**Comment by roiding** [comment]
> 这个里面需要什么变量？可以告知一下吗

我readme里面写了啊 就需要一个key 是warp+的licence
或者不写变量的话就需要自己登陆

**Comment by roiding** [comment]
我是封装了端口转发的 使用的话还是默认的50000端口

这样可以用于docker-compose的容器间通信 不用暴露端口

**Comment by roiding** [comment]
如果只是想翻墙的话，不用自己装warp客户端，直接使用wireguard就行

这个更多是用来做netflix、openai的解锁
